function Get-ADOWorkItem
{
    param(
    [Parameter(Mandatory,ValueFromPipelineByPropertyName)]
    [Alias('Org')]
    [string]
    $Organization,

    [Parameter(Mandatory,ValueFromPipelineByPropertyName)]
    [string]
    $Project,

    [Parameter(Mandatory,ParameterSetName='ByID',ValueFromPipelineByPropertyName)]
    [string]
    $ID,

    [Parameter(Mandatory,ParameterSetName='ByQuery',ValueFromPipelineByPropertyName)]
    [string]
    $Query,

    [Parameter(ValueFromPipelineByPropertyName)]
    [Alias('Fields','Select')]
    [string[]]
    $Field,

    [Parameter(ValueFromPipelineByPropertyName)]
    [uri]
    $Server = "https://dev.azure.com/",

    [string]
    $ApiVersion = "5.1",

    # A Personal Access Token    
    [Alias('PAT')]
    [string]
    $PersonalAccessToken,

    # Specifies a user account that has permission to send the request. The default is the current user.
    # Type a user name, such as User01 or Domain01\User01, or enter a PSCredential object, such as one generated by the Get-Credential cmdlet.
    [pscredential]
    [Management.Automation.CredentialAttribute()]
    $Credential,

    # Indicates that the cmdlet uses the credentials of the current user to send the web request.
    [Alias('UseDefaultCredential')]
    [switch]
    $UseDefaultCredentials,
    
    # Specifies that the cmdlet uses a proxy server for the request, rather than connecting directly to the Internet resource. Enter the URI of a network proxy server.
    [uri]
    $Proxy,

    # Specifies a user account that has permission to use the proxy server that is specified by the Proxy parameter. The default is the current user.
    # Type a user name, such as "User01" or "Domain01\User01", or enter a PSCredential object, such as one generated by the Get-Credential cmdlet.
    # This parameter is valid only when the Proxy parameter is also used in the command. You cannot use the ProxyCredential and ProxyUseDefaultCredentials parameters in the same command.
    [pscredential]
    [Management.Automation.CredentialAttribute()]
    $ProxyCredential,

    # Indicates that the cmdlet uses the credentials of the current user to access the proxy server that is specified by the Proxy parameter.
    # This parameter is valid only when the Proxy parameter is also used in the command. You cannot use the ProxyCredential and ProxyUseDefaultCredentials parameters in the same command.
    [switch]
    $ProxyUseDefaultCredentials
    )

    begin {
        $invokeRestApi = [Management.Automation.CommandMetaData]$ExecutionContext.SessionState.InvokeCommand.GetCommand('Invoke-ADORestAPI', 'Function')
        #region Copy Invoke-ADORestAPI parameters
        $invokeParams = @{} + $PSBoundParameters
        foreach ($k in @($invokeParams.Keys)) {
            if (-not $invokeRestApi.Parameters.ContainsKey($k)) {
                $invokeParams.Remove($k)
            }            
        }
        #endregion Copy Invoke-ADORestAPI parameters

        $progressId = [Random]::new().Next()
    }

    process { 
        
        if ($PSCmdlet.ParameterSetName -eq 'ByID') {
            $uri = "$Server".TrimEnd('/'), $Organization, $Project, "_apis/wit/workitems", "${ID}?" -join '/'
            $uri += @(if ($Field) {
               "fields=$($Field -join ',')"
            }
            if ($ApiVersion) {
                "api-version=$ApiVersion"
            }) -join '&'

            $invokeParams["Uri"] = $uri
            $restResponse = Invoke-ADORestAPI @invokeParams
            if (-not $restResponse.fields) { return }
            $out = $restResponse.fields
            $out.pstypenames.clear()
            $workItemType = $out.'System.WorkItemType'
            if ($workItemType) {
                $out.pstypenames.add("$Organization.$Project.$workItemType")
            }
            $out.pstypenames.add("$Organization.$Project.WorkItem")
            if ($workItemType) {
                $out.pstypenames.add("PSDevOps.$workItemType")
            }
            $out.pstypenames.add("PSDevOps.WorkItem")
            $out
        } elseif ($PSCmdlet.ParameterSetName -eq 'ByQuery') {
            $uri = "$Server".TrimEnd('/'), $Organization, $Project, "_apis/wit/wiql?" -join '/'
            $uri += if ($ApiVersion) {
                "api-version=$ApiVersion"
            }

            $invokeAgain = @{} + $invokeParams # We may need to invoke multiple times, so copy the input now

            $invokeParams.Method = "POST"
            $invokeParams.Body = ConvertTo-Json @{query=$Query}
            $invokeParams["Uri"] = $uri
                        
            Invoke-ADORestAPI @invokeParams |
                Select-Object -ExpandProperty workItems |
                & { process {
                    $_.psobject.properties.add([PSNoteProperty]::new('Organization', $Organization))
                    $_.psobject.properties.add([PSNoteProperty]::new('Project', $Project))
                    $_.psobject.properties.add([PSNoteProperty]::new('Server', $Server))
                    $_.pstypenames.clear()
                    $_.pstypenames.Add("$organization.$project.WorkItem.ID")
                    $_.pstypenames.Add("PSDevOps.WorkItem.ID")
                    $_
                } } 
        }
    }
}